# Generated by Django 4.2.6 on 2023-12-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhos_arquivos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('dev', models.TextField(blank=True, null=True)),
                ('prod', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caminhos_arquivos',
            },
        ),
    ]
