# Generated by Django 4.2.6 on 2023-12-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_unico_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caminhos_arquivos',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='caminhos_arquivos',
            old_name='dev',
            new_name='assinaturas',
        ),
        migrations.RenameField(
            model_name='caminhos_arquivos',
            old_name='prod',
            new_name='caminhopadrao',
        ),
    ]
