# Generated by Django 4.2.6 on 2023-12-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_unico_web', '0002_alter_caminhos_arquivos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caminhos_arquivos',
            options={},
        ),
    ]
