# Generated by Django 4.2.6 on 2023-12-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_unico_web', '0004_veiculos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veiculos',
            table='veiculos',
        ),
    ]
