# Generated by Django 4.2.6 on 2023-12-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_unico_web', '0006_motoristas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_abastecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('veiculo', models.TextField()),
                ('motorista', models.TextField()),
                ('valor', models.TextField()),
            ],
            options={
                'db_table': 'ordemabastecimento',
            },
        ),
    ]
