# Generated by Django 4.2.6 on 2023-12-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_unico_web', '0007_ordem_abastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhos_arquivos',
            name='caminho_os',
            field=models.TextField(blank=True, null=True),
        ),
    ]
